### ISSUE TITLE
Generators async/await?

### ISSUE THREAD

**Issue by bySabi** [xolvio/meteor-core-js#1]
@Sanjo how I can enable this for browser use?
I´m currently use meteor `promise` for server side but don´t have `Promise.async` and `Promise.await` on client side.
With generators and `yield` is enought.

**Comment by ghost** [comment]
This is not polyfilled in core-js. I think Ben will include regenerators in a future version of Meteor, when it is appropriate. Regenerators is a polyfill for generators.
